# Generated by Django 5.1.4 on 2025-01-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('assigned_task', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
