# Generated by Django 5.1.4 on 2025-01-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0002_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
