# Generated by Django 5.1.4 on 2025-01-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
