# Generated by Django 5.1.4 on 2025-01-02 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0004_company_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('passing', 'Passing Interview'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_platform.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_platform.student')),
            ],
        ),
    ]
