# Generated by Django 5.1.4 on 2025-01-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0005_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='available_slots',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
